# SPDX-License-Identifier: BSD-2-Clause
"""Hybrid Python-Haskell refinement command - COMBINED VERSION"""

import subprocess
import tempfile
import os
import json
import logging
import time
from pathlib import Path

logger = logging.getLogger(__name__)

class command:
    def __init__(self, ref_dict, outputLOG=False, annoteComments=True, outputSWITCH=True):
        self.ref_dict = ref_dict
        self.outputLOG = outputLOG
        self.annoteComments = annoteComments 
        self.outputSWITCH = outputSWITCH
        logger.debug("Initializing command with ref_dict")
        
        # Use INSTANCE VARIABLES (not properties)
        self._procIds = set()  # Use underscore prefix for instance vars
        self._defCode = []     # Instance variable
        self._declCode = []    # Instance variable
        self._testCodes = []
        self.currentId = 0
        self.switchNo = 0
        
        # Try to start Haskell
        self.haskell_process = None
        self.use_haskell = False
        
        try:
            exe_path = Path(__file__).parent / "Main"
            exe = str(exe_path) if exe_path.exists() else "./refine-haskell"
            self.haskell_process = subprocess.Popen(
                [exe, "interactive"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                text=True
            )
            
            # Send initialization
            init_data = {
                'ref_dict': ref_dict,
                'flags': {
                    'outputLOG': outputLOG,
                    'annoteComments': annoteComments,
                    'outputSWITCH': outputSWITCH
                }
            }
            json_data = json.dumps(init_data)
            self.haskell_process.stdin.write(f"INIT JSON:{json_data}\n")
            self.haskell_process.stdin.flush()
            
            self.use_haskell = True
            print("Haskell refinement engine initialized")
            
        except Exception as e:
            print(f"Could not start Haskell, using Python fallback: {e}")
            self.use_haskell = False
    
    # Properties for compatibility with existing code
    @property
    def procIds(self):
        return self._procIds
    
    @property 
    def defCode(self):
        return self._defCode
    
    @property
    def declCode(self):
        return self._declCode
    
    @property
    def testCodes(self):
        return self._testCodes
    
    def setupLanguage(self):
        """ONLY THIS FUNCTION USES HASKELL initially"""
        if self.use_haskell and self.haskell_process:
            # Try Haskell first
            self.haskell_process.stdin.write("COMMAND:setupLanguage\n")
            self.haskell_process.stdin.flush()
            
            # Read response
            while True:
                line = self.haskell_process.stdout.readline().strip()
                print(f"DEBUG RAW HASKELL OUTPUT: '{line}'")
                if line.startswith("Error Missing Key"):
                    raise SystemExit()
                if line.startswith("RESPONSE:SUCCESS"):
                    print(f"Haskell handled setupLanguage: {line}")
                    return True
                
                # Small delay to prevent busy waiting
                time.sleep(1)
        else:
            # Python fallback
            print("Python handled setupLanguage")
            # ... existing Python implementation of setupLanguage ...
            return True
    
    def collectPIds(self, ln):
        """Python fallback - not using Haskell yet"""
        if ln and len(ln) > 0:
            self._procIds.add(int(ln[0]))
        print(f"Python collected PIDs: {self._procIds}")
    
    def refineSPINLine_main(self, ln):
        """Python fallback - not using Haskell yet""" 
        self.collectPIds(ln)
        print(f"Python processed: {ln}")
        # ... rest of Python refinement logic ...
    
    def test_body(self):
        """Python fallback - not using Haskell yet"""
        # IMPORTANT: This must return an iterable, not None
        # If your Python implementation doesn't have test codes yet,
        # return at least an empty list or a placeholder
        
        # Use the property accessor
        if self._testCodes:
            return self._testCodes
        else:
            # Return a simple placeholder to avoid None
            return ["// Generated by Python fallback", "// Test body placeholder"]
    
    def __del__(self):
        """Cleanup"""
        # Check if attribute exists before accessing it
        if hasattr(self, 'haskell_process') and self.haskell_process:
            try:
                self.haskell_process.terminate()
            except:
                pass