

import subprocess
import json
import time
from pathlib import Path

class HaskellCommand:
    def __init__(self, ref_dict, outputLOG, annoteComments, outputSWITCH):
        # Simple state
        self.procIds = set()
        self.defCode = []
        self.declCode = []
        
        # Start Haskell (but don't require it)
        
        try:
            exe_path = Path(__file__).parent / "refine-haskell"
            exe = str(exe_path) if exe_path.exists() else "./refine-haskell"
            self.haskell = subprocess.Popen(
                [exe, "interactive"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                text=True
            )
            print("Haskell bridge: Ready")
        except:
            print("Haskell bridge: Could not start Haskell, using Python fallback")
            
        init_data = {
            'ref_dict': ref_dict,
            'flags': {
                'outputLOG': outputLOG,
                'annoteComments': annoteComments,
                'outputSWITCH': outputSWITCH
            }
        }
        json_data = json.dumps(init_data)
        self.haskell.stdin.write(f"INIT JSON:{json_data}\n")
        self.haskell.stdin.flush()
    def setupLanguage(self):
        """ONLY THIS FUNCTION USES HASKELL"""
        if self.haskell:
            # Try Haskell first
            self.haskell.stdin.write("COMMAND:setupLanguage\n")
            self.haskell.stdin.flush()
            
            # Read response
            while True:
                line = self.haskell.stdout.readline().strip()
                print(f"DEBUG RAW HASKELL OUTPUT: '{line}'")
                time.sleep(0.5)
                if line.startswith("Error Missing Key"):
                    raise SystemExit()
                if line.startswith("RESPONSE:"):
                    print(f"Haskell handled setupLanguage: {line}")
                    return True
        else:
            # Python fallback
            print("Python handled setupLanguage")
            return True
    
    def collectPIds(self, line):
        """Python fallback - not using Haskell yet"""
        if line:
            self.procIds.add(int(line[0]))
        print(f"Python collected PIDs: {self.procIds}")
    
    def refineSPINLine_main(self, line):
        """Python fallback - not using Haskell yet""" 
        self.collectPIds(line)
        print(f"Python processed: {line}")
    
    def test_body(self):
        """Python fallback - not using Haskell yet"""
        return ["// Generated by Python fallback"]